apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend-deployment
  template:
    metadata:
      labels:
        component: frontend-deployment
    spec:
      containers:
      - name: frontend
        image: amdadulbari/optimizers-frontend:23bd857
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: amdadul-reg-cred 


---

apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport-service
spec:
  type: NodePort
  selector:
    component: frontend-deployment
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30006
