apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend-deployment
  template:
    metadata:
      labels:
        component: frontend-deployment
    spec:
      containers:
      - name: frontend
        image: amdadulbari/optimizers-frontend:d334628
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: amdadul-reg-cred
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      



---

apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport-service
spec:
  type: NodePort
  selector:
    component: frontend-deployment
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30006
